AdminBackend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from AdminBackend import views as core_views
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from .views import ApiEndpoint
from .views import secret_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/hello', ApiEndpoint.as_view()),
    url(r'^secret$', secret_page, name='secret'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^exercises/', include('WBBackend.urls')),
    url(r'^testExerciseApi/',include('WBBackend.request_api.exercise_urls')),
    url(r'^testWorkoutApi/',include('WBBackend.request_api.workout_urls')),
    url(r'^testProgressPhotoApi/',include('WBBackend.request_api.progress_photo_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WBBackend/urls.py
from django.conf.urls import url
from . import views
from WBBackend.views import CreateSubWorkout,\
    ViewDefaultExercises,ExerciseDescription,CustomExerciseDescription,SubWorkoutList,MainWorkoutList,ViewExerciseGoals,\
    ProgressPhotosList,ViewProgressPhotos
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls.static import static

app_name = 'WBBackend'

urlpatterns = [
    url(r'^$', ViewDefaultExercises.as_view(), name='exercises'),
    url(r'^(?P<pk>[0-9]+)/$', ExerciseDescription.as_view(), name='exercise_description'),
    url(r'^(?P<pk>[0-9]+)/test/$', CustomExerciseDescription.as_view(), name='custom_exercise_description'),
    #url(r'^createmainworkout/', views.createMainWorkout, name='create_mainworkout'),
    url(r'^createsubworkout/', CreateSubWorkout.as_view(), name='create_subworkout'),
   # url(r'createExercise/', views.createExercise, name='create_exercise'),
    url(r'subworkouts/', SubWorkoutList.as_view(), name='subworkout_list'),
    url(r'mainworkouts/', MainWorkoutList.as_view(), name='mainworkout_list'),
    url(r'^(?P<pk>[0-9]+)/exercisegoals/$', ViewExerciseGoals.as_view(), name='exercise_goals'),
    #url(r'createProgressPhoto/',views.createProgressPhoto, name='create_progress_photo'),
    url(r'progressphotos/',ProgressPhotosList.as_view(), name='progress_photo_list'),
    url(r'^(?P<pk>[0-9]+)/progress_photo/$', ViewProgressPhotos.as_view(), name='progress_photo'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

WorkoutBuddy/urls.py
from django.conf.urls import url
import WorkoutBuddy.views
from WorkoutBuddy.views import CreateSubWorkout,\
    ViewDefaultExercises,ExerciseDescription,CustomExerciseDescription,SubWorkoutList,MainWorkoutList,ViewExerciseGoals,\
    ProgressPhotosList,ViewProgressPhotos

from django.conf import settings
from django.conf.urls.static import static

app_name = 'WorkoutBuddy'

urlpatterns = [
    url(r'^$', ViewDefaultExercises.as_view(), name='exercises'),
    url(r'^(?P<pk>[0-9]+)/$', ExerciseDescription.as_view(), name='exercise_description'),
    url(r'^(?P<pk>[0-9]+)/test/$', CustomExerciseDescription.as_view(), name='custom_exercise_description'),
    url(r'^createmainworkout/', WorkoutBuddy.views.createMainWorkout, name='create_mainworkout'),
    url(r'^createsubworkout/', CreateSubWorkout.as_view(), name='create_subworkout'),
    url(r'createExercise/', WorkoutBuddy.views.createExercise, name='create_exercise'),
    url(r'subworkouts/', SubWorkoutList.as_view(), name='subworkout_list'),
    url(r'mainworkouts/', MainWorkoutList.as_view(), name='mainworkout_list'),
    url(r'^(?P<pk>[0-9]+)/exercisegoals/$', ViewExerciseGoals.as_view(), name='exercise_goals'),
    url(r'createProgressPhoto/', WorkoutBuddy.views.createProgressPhoto, name='create_progress_photo'),
    url(r'progressphotos/',ProgressPhotosList.as_view(), name='progress_photo_list'),
    url(r'^(?P<pk>[0-9]+)/progress_photo/$', ViewProgressPhotos.as_view(), name='progress_photo'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WorkoutBuddySite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from WorkoutBuddySite import views as core_views
from django.conf import settings
from django.conf.urls.static import static
import WorkoutBuddySite.views as view



urlpatterns = [
    url(r'android_login',view.android_login),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'exercises/', include('WorkoutBuddy.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WBBackend/forms.py
from django import forms
from WBBackend.models import CustomExercise,MainWorkout,ExerciseGoals,ProgressPhoto

class CreateExerciseForm(forms.ModelForm):#Edit this
    exercise_image = forms.ImageField(label="Exercise Image")
    class Meta:
        model = CustomExercise
        fields = ['exercise_name','exercise_description']

class CreateMainWorkoutForm(forms.ModelForm):
    class Meta:
        model = MainWorkout
        fields = ['main_workout_name']

class CreateProgressPhotoForm(forms.ModelForm):
    class Meta:
        model = ProgressPhoto
        fields = ['photo']

WBBackend/views.py
from WBBackend.models import MainWorkout,SubWorkout,DefaultExercise,CustomExercise,Profile,ExerciseGoals,ProgressPhoto,user_local_directory_image_path, Workout, WorkoutExercise, Set
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.
import datetime
from  WBBackend.request_handlers import workout_requests
from .forms import CreateExerciseForm , CreateMainWorkoutForm , CreateProgressPhotoForm
#will be altered massively
@login_required(login_url='/login/')
def createProgressPhoto(request):
    if request.method == 'POST':
        form = CreateProgressPhotoForm(request.POST, request.FILES)

        if form.is_valid():
            photo = form.cleaned_data.get('photo')
            i = datetime.datetime.now()
            date_time = '%s-%s-%s %s:%s:%s' % (i.year, i.month, i.day, i.hour, i.minute, i.second)
            progress_photo = ProgressPhoto(date_time=date_time)
            progress_photo.save()
            user = request.user
            progress_photo.user = user
            progress_photo.photo = photo
            user_profile = Profile.objects.get(user=user)
            local_path = user_local_directory_image_path(photo.name)
            progress_photo. local_photo = local_path
            progress_photo.user_profile = user_profile
            progress_photo.save()
            return HttpResponseRedirect('/exercises/progressphotos/')
    else:
        form = CreateProgressPhotoForm()
    return render(request, 'WBBackend/create_progress_photo.html', {'form': form})

@login_required(login_url='/login/')
def createExercise(request):
    if request.method == 'POST':
        form = CreateExerciseForm(request.POST, request.FILES)

        if form.is_valid():
            ex_image = form.cleaned_data.get('exercise_image')
            ex_name = form.cleaned_data.get('exercise_name')
            ex_description = form.cleaned_data.get('exercise_description')
            ce = CustomExercise(exercise_name=ex_name, exercise_description=ex_description)
            ce.save()
            user = request.user
            ce.exercise_image = ex_image
            ce.local_exercise_image \
                = ce.user_local_directory_exercise_image_path(filename=ex_image.name)
            ce.user = user
            ce.save()
            return HttpResponseRedirect('/exercises/')
    else:
        form = CreateExerciseForm()
    return render(request, 'WBBackend/create_exercise.html', {'form': form})

@login_required(login_url='/login/')
def createMainWorkout(request):
    if request.method == 'POST':

        form = CreateMainWorkoutForm(request.POST)
        if form.is_valid():
           main_workout_name = form.cleaned_data.get('main_workout_name')
           main_workout = MainWorkout(main_workout_name=main_workout_name)
           main_workout.save()
           user = request.user
           main_workout.user_profile = Profile.objects.get(user=user)
           main_workout.save()
           return HttpResponseRedirect('/subworkouts/')
    else:
        form = CreateMainWorkoutForm()
    return render(request, 'WBBackend/create_mainworkout.html', {'form': form})

class ViewDefaultExercises(generic.ListView):#base add exercise goals off of this
    template_name = 'WBBackend/exercise_list.html'
    model = DefaultExercise
    context_object_name = 'exercise_list'

    def get_context_data(self, **kwargs):#needs editing
        context = super(ViewDefaultExercises,self).get_context_data(**kwargs)
        context['ce_list'] = CustomExercise.objects.order_by('exercise_name')
        return context

class ExerciseDescription(generic.DetailView):
    model = DefaultExercise
    context_object_name = 'exercise'
    template_name = 'WBBackend/exercise_description.html'

class CustomExerciseDescription(generic.DetailView):
    model = CustomExercise
    context_object_name = 'exercise'
    template_name = 'WBBackend/custom_exercise_description.html'

class CreateSubWorkout(generic.CreateView):#on save go to page too add exercise goals
    template_name = 'WBBackend/create_subworkout.html'
    model = SubWorkout
    fields = ['main_workout','sub_workout_name']

class SubWorkoutList(generic.ListView):
    template_name = 'WBBackend/subworkout_list.html'
    model = SubWorkout#includde link to page with all exercises and goals with links to ex descriptions
    context_object_name = 'subworkout_list'

class MainWorkoutList(generic.ListView):
    template_name = 'WBBackend/mainworkout_list.html'
    model = MainWorkout#include link to page with sub workouts
    context_object_name = 'mainworkout_list'

class ViewExerciseGoals(generic.ListView):
    template_name = 'WBBackend/exercise_goals.html'
    model = ExerciseGoals
    context_object_name = 'exercise_list'

    def get_context_data(self, **kwargs):
        context = super(ViewExerciseGoals, self).get_context_data(**kwargs)
        id = self.kwargs['pk']
        subworkout = SubWorkout.objects.get(id=id)
        context['exercise_list'] = ExerciseGoals.objects.filter(sub_workout=subworkout)
        return context

class CreateProgressPhoto(generic.CreateView):#use form
    template_name = 'WBBackend/'
    model = ProgressPhoto
    context_object_name = 'progress_photo'


class ProgressPhotosList(generic.ListView):
    template_name = 'WBBackend/progress_photo_list.html'
    model = ProgressPhoto
    context_object_name = 'progress_photos'

    def get_queryset(self):
        user_profile = Profile.objects.get(user=self.request.user)
        return ProgressPhoto.objects.filter(user_profile=user_profile).order_by('date_time')

class ViewProgressPhotos(generic.DetailView):#need to have list to get to this
    template_name = 'WBBackend/progress_photo.html'
    model = ProgressPhoto
    fields = ['date_time','photo']
    context_object_name = 'progress_photo'






#all of this are not filling in all needed fields
class S(generic.CreateView):#and finally this
    template_name = 'WBBackend/create_subworkout.html'
    model = Set
    fields = ['workout_exercise','set','reps','weight','unit']

class CompleteEX(generic.CreateView):#then this
    template_name = 'WBBackend/create_subworkout.html'
    model = WorkoutExercise
    fields = ['workout_tag','exercise_name','sets','rep_range']
    
class DoWorkout(generic.CreateView):#this first
    template_name = 'WBBackend/create_subworkout.html'
    model = Workout
    #of course the completed exercises portion is wrong
    fields = ['date','user_profile','sub_workout_name']
    context_object_name = 'workout'



#--this can all be done in one sql query
''' to get a completed workout: needs {
1. get workout for a date
2. get completed_exercises(WorkoutExercise)
3. get sets
4 from there get completed sets with reps and weight and unit
}

 '''
    

WBBackend/templates/WBBackend/add_exercise_goals.html
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <fieldset >
    {% block content %}
    <h2> Exercises </h2>
    <ul>
        {% for exercise in exercise_list %}
            <li>
                <input type="checkbox"> {{exercise.exercise_name}}
            </li>
        {% endfor %}
        {% for custom_exercise in custom_exercise_list %}
            <li>
                <input type="checkbox"> {{custom_exercise.exercise_name}}
            </li>
        {% endfor %}
    </ul>
        {% endblock %}
    </fieldset>
    <input type="submit" value="Save" />
</form>

WBBackend/templates/WBBackend/create_exercise.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

WBBackend/templates/WBBackend/create_mainworkout.html
<form action="" method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

WBBackend/templates/WBBackend/create_progress_photo.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

WBBackend/templates/WBBackend/create_subworkout.html
<form action="" method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

WBBackend/templates/WBBackend/custom_exercise_description.html
{% block content %}
    <h2> {{exercise.exercise_name}}</h2>
    <p> {{exercise.exercise_description}}</p>
    <h3> {{exercise.exercise_image.url}}</h3>
    {% load static %}
    <img src="{{exercise.exercise_image.url}}" style="width:300px;height:270px"/>
{% endblock %}

WBBackend/templates/WBBackend/exercise_description.html
{% block content %}
    <h2> {{exercise.exercise_name}}</h2>
    <p> {{exercise.exercise_description}}</p>
    {% load static %}
    <img src="{% static exercise.exercise_image.url %}" style="width:300px;height:270px"/>
{% endblock %}

WBBackend/templates/WBBackend/exercise_goals.html
{% block content %}
    <h2> Exercise Goals </h2>
    <ul>
        {% for exercise in exercise_list %}
            {% if exercise.default_exercise %}
        <h4>{{exercise.default_exercise.exercise_name}}</h4>
            {% endif %}

            {% if exercise.custom_exercise %}
        <h6>{{exercise.custom_exercise.exercise_name}}</h6>
            {% endif %}

        <h7>Goal Sets: {{exercise.goal_sets}} Goal Reps: {{exercise.goal_reps}}</h7>
        {% endfor %}
    </ul>
{% endblock %}

WBBackend/templates/WBBackend/exercise_list.html
{% block content %}
    <h2> Exercises </h2>
    <ul>
       {% for exercise in exercise_list %}
            <li>
                <a href="{% url 'WBBackend:exercise_description' exercise.id %}">
                    {{exercise.exercise_name}}
                </a>
            </li>
        <input type="checkbox"> {{exercise.exercise_name}}
        {% endfor %}
        {% for custom_exercise in custom_exercise_list %}
            <li>
                <a href="{% url 'WBBackend:custom_exercise_description' exercise.id %}">
                    {{custom_exercise.exercise_name}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

WBBackend/templates/WBBackend/homepage.html
<!DOCTYPE>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>


    .bottomNav {
        text-align: center;
        overflow: hidden;
        background-color: black;
        position: absolute;
        right: 5px;
        bottom: 5px;
        left: 5px;
        padding: 1rem;
    }

.navbar {
    overflow: hidden;
    background-color: #333;
    font-family: Arial;
}

.navbar a {
    float: left;
    font-size: 16px;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

.dropdown {
    float: left;
    overflow: hidden;
}

.dropdown .dropbtn {
    font-size: 16px;
    border: none;
    outline: none;
    color: white;
    padding: 14px 16px;
    background-color: inherit;
}

.loginbtn {
    position: absolute;
    right: 1%;
    font-size: 16px;
    border: none;
    outline: none;
    color: white;
    padding: 14px 16px;
    background-color: inherit;
}

.navbar a:hover, .dropdown:hover .dropbtn,.dropdown:hover .loginbtn {
    background-color: red;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    float: none;
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}

.dropdown-content a:hover {
    background-color: #ddd;
}

.dropdown:hover .dropdown-content {
    display: block;
}

</style>
</head>

<body>
<div class="navbar">

  <div class="dropdown" >
    <button class="dropbtn">Exercise
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">All Exercises</a>
      <a href="#">Default Exercise</a>
      <a href="#">Custom Exercises</a>
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Workout Stats</button>
  </div>



  <div class="dropdown" >
    <button class="dropbtn">Workout
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="#">All Workouts</a>
      <a href="#">Default Workouts</a>
      <a href="#">Custom Workouts</a>
    </div>
  </div>

   <div class="dropdown">
    <button class="dropbtn">Progress Photos</button>
  </div>

  <div class="dropdown">
    <button class="loginbtn" style="float:right">Login</button>
  </div>

  <!- should be a button right now -->
</div>
<div style="border: 2px solid blue;align-text: right; padding-left: 300px;padding-right: 300px;height: 85%;">
  <h1 style="text-align: center;vertical-align: middle;">WorkoutBuddy</h1>
  <p style="text-align: center;vertical-align: middle;">Some content..<p><!- add intro here -->
</div>


<div class="bottomNav"><!- add terms and shit, and link to android app --
  <p style="color: white;">Some content..</p>
</div>

</body>
</html>

WBBackend/templates/WBBackend/mainworkout_list.html
{% block content %}
    <h2> MainWorkouts </h2>
    <ul>
        {% for mainworkout in mainworkout_list %}
        <li>
            <h4>{{mainworkout.main_workout_name}}</h4>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

WBBackend/templates/WBBackend/progress_photo.html
{% block content %}
    <h2> {{progress_photo.date_time}}</h2>
    {% load static %}
    <img src="{{progress_photo.photo.url}}" style="width:300px;height:400px"/>
{% endblock %}

WBBackend/templates/WBBackend/progress_photo_list.html
{% block content %}
    <h2> Progress Photos </h2>
    <ul>
        {% for photo in progress_photos %}
            <li>
                <a href="{% url 'WorkoutBuddy:progress_photo' photo.id %}">
                    {{photo.date_time}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

WBBackend/templates/WBBackend/subworkout_list.html
{% block content %}
    <h2> SubWorkouts </h2>
    <ul>
        {% for subworkout in subworkout_list %}
        <li>
            <a href="{% url 'WorkoutBuddy:exercise_goals' subworkout.id %}">
                {{subworkout.main_workout.main_workout_name}} -> {{subworkout.sub_workout_name}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}